- org: Meta
  type: Company
  country: US
  focus: [LLM, Multimodal, Open-source models]
  hf_accounts:
    - meta-llama
    - facebook

- org: BAAI
  type: Non-Profit
  country: CN
  focus: [Multimodal, Open-source, Embodied Intelligence]
  hf_accounts:
    - BAAI
    - FalgRelease
    - CofeAI
    - OmniGen2
    - RoboCOIN
  ms_accounts:
    - BAAI
    - RoboCOIN
